### PR TITLE
improve plugin setting page

### PR DESCRIPTION
**Pull request by ooker777**

### CODE REVIEW

**Review by Lisandra-dev — CHANGES_REQUESTED** [review]
I prefer to remove this. A last leaves a link into the plugin for user to see issue.

On my side, with ezlinks and wikilinks, I don't have any bug.

Plus, work is in progress to make a plugin to make Obsidian feature into one big Mkdocs plugin that supports everything.

**Review by Lisandra-dev — CHANGES_REQUESTED** [review]
Same as above. Prefer leave a link to the issue or let user to search for it.

In conclusion I'm not a big fan of know issue file because I can move a lot and user can misunderstand the project.

**Review by Lisandra-dev — APPROVED** [review]

**Comment by ooker777** [comment]
so basically you are fine with the "Plugin Settings" page improvement proposal, and only against the "Known issues" page? Is there a way to accept only change on one commit and regard the other on your side? I haven't had a chance to test functions on the receiving end.

**Comment by Lisandra-dev** [comment]
Not surprised by GitHub bug. This feature is difficult to use. :')

**Comment by Lisandra-dev** [comment]
I think I could validate like that ?

**Comment by ooker777** [comment]
here is how I see now

**Comment by Lisandra-dev** [comment]
Ignore the netlify checking, I need to fix it on my side :')

**Pull request merged**
